### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justinegeffen**
## Changes
- [x] Update README.md

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Change LGTM

Regarding " Security Vulnerability Disclosure": Why is this section special for this plugin? Should we link to https://mattermost.com/security-vulnerability-report/ instead?

**Comment by justinegeffen** [comment]
Good catch, @hanzei. Updated.

**Comment by nathanaelhoun** [comment]
@justinegeffen Can we keep a link to `CONTRIBUTING.md` in the README please?

**Comment by justinegeffen** [comment]
> @justinegeffen Can we keep a link to `CONTRIBUTING.md` in the README please?

Happy to! :) Are you open to including a link to the Gitbook page (which has all the same content)? Or specifically to that .md file?

**Comment by nathanaelhoun** [comment]
We can include a link to the gitbook page if you prefer (and delete the CONTRIBUTING.md file to avoid duplication)!

**Review by hanzei — APPROVED** [review]

**Review by nathanaelhoun — APPROVED** [review]
Oh it's already done, great!

**Pull request merged**
