### PR TITLE
Encrypt tokens at Rest

### LINKED ISSUE #5: CircleCI tokens should be encrypted
**Describe the bug**

Currently, the plain tokens are stored in the KVStore.

**Expected behavior**

They should be encrypted, similarly than the [Github Plugin is doing](https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/plugin.go#L239)

### PR DESCRIPTION
**Pull request by nathanaelhoun**
## Changes

- [x] Encrypt stored tokens 
- [x] Update README.md

After this, users should log again to CircleCI as the token were not encrypted

Fixes #5

### CODE REVIEW

**Comment by darkLord19** [comment]
I didn't quite get how encryption key will be provided to plugin @nathanaelhoun

**Comment by nathanaelhoun** [comment]
@darkLord19 It's set in `config.json`
image

**Comment by darkLord19** [comment]
Oh got it. I misread docs and thought we need to generate it from circleci dashboard. But after re reading it I get it. So by default we will be generating a random key when user connects to a token and the later user can regenerate it from console ui, correct?

**Comment by darkLord19** [comment]
I see first time user needs to explicitly create both webhook and encryption key. I can understand about not generating webhook secret not automatically but i think we should automatically generate encryption key upon installation or when user calls /connect command. Seems more user friendly.

**Comment by nathanaelhoun** [comment]
Yes you got it. 
I see the same problem as you. I have asked the question in the [~toolkit channel](https://community-daily.mattermost.com/core/pl/83p3945wnjnetgcm7thja9kqfo) on Community. I think we should keep it as it for the moment as it's the way others plugins, like the github one, works

**Review by darkLord19 — APPROVED** [review]

**Comment by darkLord19** [comment]
> Yes you got it.
> I see the same problem as you. I have asked the question in the [~toolkit channel](https://community-daily.mattermost.com/core/pl/83p3945wnjnetgcm7thja9kqfo) on Community. I think we should keep it as it for the moment as it's the way others plugins, like the github one, works

In that case looks fine. we can merge.

**Pull request merged**
