### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by hanzei**
Cut a release for the Marketplace

Part of https://github.com/mattermost/mattermost-plugin-circleci/issues/75

### CODE REVIEW

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-circleci/pull/78 is required before we can cut a release

**Comment by nathanaelhoun** [comment]
@hanzei I wanted to make some in-plugin documentation changes as suggested in #68, I will do them in the next hours and send a PR :-) If we could include it in v1.2.0 it would be great!

**Comment by hanzei** [comment]
@nathanaelhoun Are the changes only to the files in `docs/` or code changes? If it's the former they are not tied to a release.

**Review by catalintomai — APPROVED** [review]

**Comment by nathanaelhoun** [comment]
@hanzei These are changes in the code strings

**Comment by nathanaelhoun** [comment]
@hanzei I have opened #79 for small code changes for this release :smile:

**Comment by aaronrothschild** [comment]
@jfrerich and @DHaussermann ping on this - hoping to get a release today.  :)

**Review by DHaussermann — APPROVED** [review]
Tested and passed
I have run through the initial intake testing again. In summary: 
- Tested connect / disconnect on browser and desktop
- Tested setting and updating default project as well as ensuring it is used correctly for project commands such as managing variables
- Tested Project commands 
- Tested `pipeline`, `workflow` and `insight` commands that return data 
- Tested `workflow` commands to rerun and cancel workflows
- Tested managing subscriptions along with corresponding orb
- Ensured subscriptions can post always or only on failure as per config. 
- Version number correctly bumped to `1.2.0` :)

I did come across 2 minor issues https://github.com/mattermost/mattermost-plugin-circleci/issues/81 and https://github.com/mattermost/mattermost-plugin-circleci/issues/82 we should triage to see about addressing in a future  release. 
LGTM!

Detailed test cases for this are being finalized and will be imported into Zephyr soon.

**Comment by hanzei** [comment]
Given that there are little changes in this PR, I'm going to merge it now despite one dev review missing.

**Pull request merged**
